//! Generates the `bn254_x5` width-6 constant table that `src/lib.rs` includes,
//! by running `light-poseidon` on the host and writing its parameters out as
//! data. The crate docs in `src/lib.rs` give the reason.

use std::{env, fs, path::Path};

use ark_ed_on_bn254::Fq;
use ark_ff::{BigInteger256, PrimeField};
use light_poseidon::parameters::bn254_x5::get_poseidon_parameters;

/// The one state width this crate serves: arity 5 plus the domain tag.
const WIDTH: u8 = 6;

/// The S-box exponent of circomlib's `bn254_x5` instance.
const ALPHA: u64 = 5;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");

    let width = usize::from(WIDTH);
    let p = get_poseidon_parameters::<Fq>(WIDTH)
        .expect("light-poseidon publishes bn254_x5 parameters for every width in 2..=13");

    // The shape the vendored `circom.rs` in `poseidon-wasm` assumes. Asserted so
    // a light-poseidon bump that changes it fails the build, not the digests.
    assert_eq!(p.width, width);
    assert_eq!(p.alpha, ALPHA);
    assert_eq!(p.ark.len(), width * (p.full_rounds + p.partial_rounds));
    assert_eq!(p.mds.len(), width);
    assert!(p.mds.iter().all(|row| row.len() == width));

    let table = format!(
        "// @generated by build.rs from light-poseidon's bn254_x5 tables. Do not edit.\n\
         pub(crate) const WIDTH: usize = {width};\n\
         pub(crate) const ALPHA: u64 = {};\n\
         pub(crate) const FULL_ROUNDS: usize = {};\n\
         pub(crate) const PARTIAL_ROUNDS: usize = {};\n\
         {}{}",
        p.alpha,
        p.full_rounds,
        p.partial_rounds,
        table_literal("ARK", &p.ark),
        table_literal("MDS", &p.mds.concat()),
    );

    let dst = Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("bn254_x5_w6.rs");
    fs::write(dst, table).expect("write the generated parameter table");
}

/// A field element as the canonical little-endian limbs that
/// `From<BigInteger256>` reads back — the encoding `decode` in `src/lib.rs`
/// inverts. Checked here so a mismatch is a build failure, not a bad digest.
fn limbs(f: &Fq) -> [u64; 4] {
    let limbs = f.into_bigint().0;
    assert_eq!(
        Fq::from(BigInteger256::new(limbs)),
        *f,
        "limbs must round-trip through the decoder in src/lib.rs"
    );
    limbs
}

/// `name` as a `[[u64; 4]; N]` literal, one row per field element.
fn table_literal(name: &str, elements: &[Fq]) -> String {
    let rows: String = elements
        .iter()
        .map(limbs)
        .map(|[a, b, c, d]| format!("    [{a}, {b}, {c}, {d}],\n"))
        .collect();
    format!(
        "pub(crate) static {name}: [[u64; 4]; {}] = [\n{rows}];\n",
        elements.len()
    )
}
