//! Generates the `bn254_x5` constant tables that `src/lib.rs` includes, by
//! running `light-poseidon` on the host and writing its parameters out as
//! data. The crate docs in `src/lib.rs` give the reason.

use std::{env, fs, path::Path};

use ark_ed_on_bn254::Fq;
use ark_ff::{BigInteger256, PrimeField};
use light_poseidon::parameters::bn254_x5::get_poseidon_parameters;

/// The state widths this crate serves: arities 1 to 6 plus the domain tag.
const WIDTHS: std::ops::RangeInclusive<u8> = 2..=7;

/// The S-box exponent of circomlib's `bn254_x5` instance.
const ALPHA: u64 = 5;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");

    let mut statics = String::new();
    let mut entries = String::new();
    for w in WIDTHS {
        let width = usize::from(w);
        let p = get_poseidon_parameters::<Fq>(w)
            .expect("light-poseidon publishes bn254_x5 parameters for every width in 2..=13");

        // The shape the vendored `circom.rs` in `poseidon-wasm` assumes. Asserted so
        // a light-poseidon bump that changes it fails the build, not the digests.
        assert_eq!(p.width, width);
        assert_eq!(p.alpha, ALPHA);
        assert_eq!(p.ark.len(), width * (p.full_rounds + p.partial_rounds));
        assert_eq!(p.mds.len(), width);
        assert!(p.mds.iter().all(|row| row.len() == width));

        statics.push_str(&table_literal(&format!("ARK_{width}"), &p.ark));
        statics.push_str(&table_literal(&format!("MDS_{width}"), &p.mds.concat()));
        entries.push_str(&format!(
            "    Table {{ width: {width}, full_rounds: {}, partial_rounds: {}, \
             ark: &ARK_{width}, mds: &MDS_{width} }},\n",
            p.full_rounds, p.partial_rounds,
        ));
    }

    let table = format!(
        "// @generated by build.rs from light-poseidon's bn254_x5 tables. Do not edit.\n\
         pub(crate) const ALPHA: u64 = {ALPHA};\n\
         pub(crate) const MIN_WIDTH: usize = {};\n\
         pub(crate) const MAX_WIDTH: usize = {};\n\
         {statics}\
         pub(crate) static TABLES: [Table; {}] = [\n{entries}];\n",
        WIDTHS.start(),
        WIDTHS.end(),
        WIDTHS.count(),
    );

    let dst = Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("bn254_x5.rs");
    fs::write(dst, table).expect("write the generated parameter tables");
}

/// A field element as the canonical little-endian limbs that
/// `From<BigInteger256>` reads back — the encoding `decode` in `src/lib.rs`
/// inverts. Checked here so a mismatch is a build failure, not a bad digest.
fn limbs(f: &Fq) -> [u64; 4] {
    let limbs = f.into_bigint().0;
    assert_eq!(
        Fq::from(BigInteger256::new(limbs)),
        *f,
        "limbs must round-trip through the decoder in src/lib.rs"
    );
    limbs
}

/// `name` as a `[[u64; 4]; N]` literal, one row per field element.
fn table_literal(name: &str, elements: &[Fq]) -> String {
    let rows: String = elements
        .iter()
        .map(limbs)
        .map(|[a, b, c, d]| format!("    [{a}, {b}, {c}, {d}],\n"))
        .collect();
    format!(
        "static {name}: [[u64; 4]; {}] = [\n{rows}];\n",
        elements.len()
    )
}
