import { readFileSync } from "node:fs";
import { beforeAll, describe, expect, it } from "vitest";
import { bytesToHex, hexToBytes } from "../core/hex.js";
import { BABYJUB_SUBGROUP_ORDER, Jubjub, Poseidon } from "../crypto/index.js";
import {
    decodeClue,
    encodeClue,
    FMD_DEFAULT_GAMMA,
    FMD_DOMAIN,
    fmdFlag,
    fmdFlagKeyFromDetection,
    fmdTest,
} from "./fmd.js";

describe("FMD (Niwl)", () => {
    let J: Jubjub;
    let P: Poseidon;
    beforeAll(async () => {
        J = await Jubjub.build();
        P = await Poseidon.build();
    });

    function rng(seed: bigint) {
        let s = seed;
        return () => {
            s = (s * 6364136223846793005n + 1442695040888963407n) & ((1n << 128n) - 1n);
            return s % BABYJUB_SUBGROUP_ORDER;
        };
    }

    it("self-detection always succeeds", () => {
        const r = rng(1n);
        const dk = { x: [r(), r(), r(), r(), r()] };
        const fk = fmdFlagKeyFromDetection(J, dk);
        for (let trial = 0; trial < 16; trial++) {
            const clue = fmdFlag(J, P, fk, r());
            expect(fmdTest(J, P, dk, clue)).toBe(true);
        }
    });

    it("foreign detection statistically near 2^-γ", { timeout: 120_000 }, () => {
        const N = 256;
        const γ = FMD_DEFAULT_GAMMA;
        const ra = rng(0xa1n),
            rb = rng(0xb2n);
        const dkA = { x: Array.from({ length: γ }, () => ra()) };
        const dkB = { x: Array.from({ length: γ }, () => rb()) };
        const fkA = fmdFlagKeyFromDetection(J, dkA);
        let hits = 0;
        for (let i = 0; i < N; i++) {
            const clue = fmdFlag(J, P, fkA, ra());
            if (fmdTest(J, P, dkB, clue)) hits++;
        }
        // E[hits] = N · 2^-γ = 256/32 = 8. Tolerate up to 4× expectation.
        expect(hits).toBeLessThan(N / 2);
    });

    it("encode / decode round-trip", () => {
        const r = rng(42n);
        const dk = { x: [r(), r(), r()] };
        const fk = fmdFlagKeyFromDetection(J, dk);
        const clue = fmdFlag(J, P, fk, r());
        const enc = encodeClue(clue);
        const dec = decodeClue(enc);
        expect(dec.gamma).toBe(clue.gamma);
        expect(Array.from(dec.R)).toEqual(Array.from(clue.R));
        expect(Array.from(dec.bits)).toEqual(Array.from(clue.bits));
        expect(fmdTest(J, P, dk, dec)).toBe(true);
    });
});

// ── cross-language vectors ───────────────────────────────────────────────
//
// `tests/vectors/fmd.json` is generated by `npm run gen:vectors` and exists
// to pin the FMD v3 byte order against the Rust indexer. Nothing read it:
// this suite generated its own values with a local LCG instead, so the
// cross-language guarantee the module header claims was asserted in prose
// only. These tests are what make it real.
describe("cross-language vectors (tests/vectors/fmd.json)", () => {
    let J: Jubjub;
    let P: Poseidon;
    beforeAll(async () => {
        J = await Jubjub.build();
        P = await Poseidon.build();
    });

    const vectors = JSON.parse(
        readFileSync(new URL("../../tests/vectors/fmd.json", import.meta.url), "utf8"),
    ) as {
        version: number;
        domain: string;
        vectors: {
            label: string;
            gamma: number;
            dk_x: string[];
            fk_X: { x: string; y: string }[];
            r: string;
            clue_R: string;
            clue_bits: string;
            clue_encoded: string;
            detect_self: boolean;
            detect_other: boolean;
        }[];
    };

    it("matches the scheme version the fixture was generated for", () => {
        expect(vectors.version).toBe(3);
        expect(vectors.domain).toBe(FMD_DOMAIN);
    });

    for (const v of vectors.vectors) {
        describe(v.label, () => {
            it("derives the recorded flag key from the detection key", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const fk = fmdFlagKeyFromDetection(J, dk);
                expect(fk.X.map((p) => ({ x: p[0].toString(), y: p[1].toString() }))).toEqual(
                    v.fk_X,
                );
            });

            it("reproduces the recorded clue byte-for-byte", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const fk = fmdFlagKeyFromDetection(J, dk);
                const clue = fmdFlag(J, P, fk, BigInt(v.r));

                expect(bytesToHex(clue.R)).toBe(v.clue_R);
                expect(bytesToHex(clue.bits)).toBe(v.clue_bits);
                expect(bytesToHex(encodeClue(clue))).toBe(v.clue_encoded);
                expect(clue.gamma).toBe(v.gamma);
            });

            it("detects with the owning key and not with another", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const clue = decodeClue(hexToBytes(v.clue_encoded));

                expect(fmdTest(J, P, dk, clue)).toBe(v.detect_self);

                const other = { x: v.dk_x.map((x) => BigInt(x) + 1n) };
                expect(fmdTest(J, P, other, clue)).toBe(v.detect_other);
            });
        });
    }
});
