import { readFileSync } from "node:fs";
import { beforeAll, describe, expect, it } from "vitest";
import { bytesToHex, hexToBytes } from "../core/hex.js";
import { BABYJUB_SUBGROUP_ORDER, Jubjub, Poseidon } from "../crypto/index.js";
import { FMD_DOMAIN, fmdFlagOnBase, fmdTest } from "./clue.js";
import { decodeClue, encodeClue } from "./codec.js";
import { fmdDiversifiedDetectionKey, fmdDiversifiedFlagKey } from "./diversified.js";
import {
    assertDetectionGamma,
    FMD_DEFAULT_GAMMA,
    fmdFlagKeyFromDetection,
    fmdGenDetectionKey,
} from "./keys.js";

describe("detection gamma ceiling", () => {
    let J: Jubjub;
    let P: Poseidon;
    beforeAll(async () => {
        J = await Jubjub.build();
        P = await Poseidon.build();
    });

    it("a key longer than the sender gamma loses the recipient's own notes", () => {
        // Senders pack FMD_DEFAULT_GAMMA bits and zero-pad the rest, while detection tests every
        // bit of the key, so each padding bit rejects a genuine note with probability 1/2.
        const root = 0x1234_5678n;
        const base = J.base8;
        const ck = J.mulPointEscalar(base, root);
        const flag = fmdDiversifiedFlagKey(J, P, ck, base, FMD_DEFAULT_GAMMA);

        const overlong = fmdDiversifiedDetectionKey(P, root, FMD_DEFAULT_GAMMA + 3);
        const matched = Array.from({ length: 64 }, (_, i) => {
            const clue = fmdFlagOnBase(J, P, flag, base, BigInt(i) + 1n);
            // The wire prefix is 16 bits wide with the unused bits zero; a
            // longer clue is reconstructed from it server-side.
            const padded = { ...clue, gamma: overlong.x.length };
            return fmdTest(J, P, overlong, padded);
        }).filter(Boolean).length;

        // 64 at a matching gamma; ~1/8 of that at three extra bits.
        expect(matched).toBeLessThan(30);

        const exact = fmdDiversifiedDetectionKey(P, root, FMD_DEFAULT_GAMMA);
        for (let i = 0; i < 64; i++) {
            const clue = fmdFlagOnBase(J, P, flag, base, BigInt(i) + 1n);
            expect(fmdTest(J, P, exact, clue)).toBe(true);
        }
    });

    it("rejects a gamma above the sender gamma", () => {
        expect(() => assertDetectionGamma(FMD_DEFAULT_GAMMA + 1)).toThrow(/exceeds the sender/);
        expect(() => assertDetectionGamma(0)).toThrow(/positive integer/);
        expect(() => assertDetectionGamma(FMD_DEFAULT_GAMMA)).not.toThrow();
    });
});

describe("FMD (Niwl)", () => {
    let J: Jubjub;
    let P: Poseidon;
    beforeAll(async () => {
        J = await Jubjub.build();
        P = await Poseidon.build();
    });

    function rng(seed: bigint) {
        let s = seed;
        return () => {
            s = (s * 6364136223846793005n + 1442695040888963407n) & ((1n << 128n) - 1n);
            return s % BABYJUB_SUBGROUP_ORDER;
        };
    }

    it("self-detection always succeeds", () => {
        const r = rng(1n);
        const dk = { x: [r(), r(), r(), r(), r()] };
        const fk = fmdFlagKeyFromDetection(J, dk, J.base8);
        for (let trial = 0; trial < 16; trial++) {
            const clue = fmdFlagOnBase(J, P, fk, J.base8, r());
            expect(fmdTest(J, P, dk, clue)).toBe(true);
        }
    });

    it("foreign detection statistically near 2^-γ", { timeout: 120_000 }, () => {
        const N = 256;
        const γ = FMD_DEFAULT_GAMMA;
        const ra = rng(0xa1n),
            rb = rng(0xb2n);
        const dkA = { x: Array.from({ length: γ }, () => ra()) };
        const dkB = { x: Array.from({ length: γ }, () => rb()) };
        const fkA = fmdFlagKeyFromDetection(J, dkA, J.base8);
        let hits = 0;
        for (let i = 0; i < N; i++) {
            const clue = fmdFlagOnBase(J, P, fkA, J.base8, ra());
            if (fmdTest(J, P, dkB, clue)) hits++;
        }
        // E[hits] = N · 2^-γ = 256/32 = 8; the N/2 bound is deliberately loose.
        expect(hits).toBeLessThan(N / 2);
    });

    it("encode / decode round-trip", () => {
        const r = rng(42n);
        const dk = { x: [r(), r(), r()] };
        const fk = fmdFlagKeyFromDetection(J, dk, J.base8);
        const clue = fmdFlagOnBase(J, P, fk, J.base8, r());
        const enc = encodeClue(clue);
        const dec = decodeClue(enc);
        expect(dec.gamma).toBe(clue.gamma);
        expect(Array.from(dec.R)).toEqual(Array.from(clue.R));
        expect(Array.from(dec.bits)).toEqual(Array.from(clue.bits));
        expect(fmdTest(J, P, dk, dec)).toBe(true);
    });
});

// `tests/vectors/fmd.json` is generated by `npm run gen:vectors` and pins the FMD wire format
// against the Rust indexer.
describe("cross-language vectors (tests/vectors/fmd.json)", () => {
    let J: Jubjub;
    let P: Poseidon;
    beforeAll(async () => {
        J = await Jubjub.build();
        P = await Poseidon.build();
    });

    const vectors = JSON.parse(
        readFileSync(new URL("../../tests/vectors/fmd.json", import.meta.url), "utf8"),
    ) as {
        version: number;
        domain: string;
        vectors: {
            label: string;
            gamma: number;
            dk_x: string[];
            fk_X: { x: string; y: string }[];
            r: string;
            clue_R: string;
            clue_bits: string;
            clue_encoded: string;
            detect_self: boolean;
            detect_other: boolean;
        }[];
    };

    it("matches the scheme version the fixture was generated for", () => {
        expect(vectors.version).toBe(2);
        expect(vectors.domain).toBe(FMD_DOMAIN);
    });

    for (const v of vectors.vectors) {
        describe(v.label, () => {
            it("derives the recorded flag key from the detection key", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const fk = fmdFlagKeyFromDetection(J, dk, J.base8);
                expect(fk.X.map((p) => ({ x: p[0].toString(), y: p[1].toString() }))).toEqual(
                    v.fk_X,
                );
            });

            it("reproduces the recorded clue byte-for-byte", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const fk = fmdFlagKeyFromDetection(J, dk, J.base8);
                const clue = fmdFlagOnBase(J, P, fk, J.base8, BigInt(v.r));

                expect(bytesToHex(clue.R)).toBe(v.clue_R);
                expect(bytesToHex(clue.bits)).toBe(v.clue_bits);
                expect(bytesToHex(encodeClue(clue))).toBe(v.clue_encoded);
                expect(clue.gamma).toBe(v.gamma);
            });

            it("detects with the owning key and not with another", () => {
                const dk = { x: v.dk_x.map(BigInt) };
                const clue = decodeClue(hexToBytes(v.clue_encoded));

                expect(fmdTest(J, P, dk, clue)).toBe(v.detect_self);

                const other = { x: v.dk_x.map((x) => BigInt(x) + 1n) };
                expect(fmdTest(J, P, other, clue)).toBe(v.detect_other);
            });
        });
    }
});

describe("clue wire format", () => {
    const clue = (gamma: number) => ({
        gamma,
        R: new Uint8Array(32),
        bits: new Uint8Array(Math.ceil(gamma / 8)),
    });

    it("round-trips a well-formed clue", () => {
        expect(decodeClue(encodeClue(clue(5)))).toEqual(clue(5));
    });

    it("rejects trailing bytes rather than accepting a second spelling", () => {
        // A tolerant length would let distinct byte strings decode to one clue.
        const padded = new Uint8Array([...encodeClue(clue(5)), 0, 0]);
        expect(() => decodeClue(padded)).toThrow(/exactly/);
    });

    it("rejects gamma 0, which fmdTest accepts against any empty key", () => {
        const buf = encodeClue(clue(5));
        buf[0] = 0;
        expect(() => decodeClue(buf)).toThrow(/1\.\.255/);
    });

    it("refuses to encode a gamma that does not fit its byte", () => {
        // 256 would truncate to 0 on the wire.
        expect(() => encodeClue(clue(256))).toThrow(/1\.\.255/);
    });

    it("validates gamma when generating a detection key", () => {
        expect(() => fmdGenDetectionKey(() => 1n, 0)).toThrow();
        expect(() => fmdGenDetectionKey(() => 1n, -1)).toThrow();
    });
});
