#!/usr/bin/env node
// Sync src/version.ts from package.json#version. Runs as `prebuild`.
// Keeps `VERSION` export aligned with the published package version
// without manual edits.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src/version.ts");
const next = `// Auto-generated by scripts/sync-version.mjs from package.json. Do not edit.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`;

const current = (() => {
    try {
        return readFileSync(target, "utf8");
    } catch {
        return "";
    }
})();

if (current === next) process.exit(0);
writeFileSync(target, next);
console.log(`sync-version: src/version.ts → ${pkg.version}`);
